sudo: required
services:
  - docker

before_install:
  - docker build -t justman00/docker-react -f Dockerfile.dev .
script:
  - docker run justman00/docker-react npm test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-843674207314"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
